server:
 port: 9005
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: efg-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/PMDGJJW/KTC.git
          username: PMDGJJW
          password: 1999jianjun26394
  rabbitmq:
    host: 192.168.0.11
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
